from sqlalchemy import sql, orm
from app import db

class sex_by_age(db.Model):
    __tablename__='sex_by_age'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())
    male = db.Column('male', db.Integer())
    m_under5 = db.Column('m_under5', db.Integer())
    m_5to9  = db.Column('m_5to9', db.Integer())
    m_10to14  = db.Column('m_10to14', db.Integer())
    m_15to17 = db.Column('m_15to17', db.Integer())
    m_18to20 = db.Column('m_18to20', db.Integer())
    m_20  = db.Column('m_20', db.Integer())
    m_21 = db.Column('m_21', db.Integer())
    m_22to24 = db.Column('m_22to24', db.Integer())
    m_25to29 = db.Column('m_25to29', db.Integer())
    m_30to34 = db.Column('m_30to34', db.Integer())
    m_35to39 = db.Column('m_35to39', db.Integer()) 
    m_40to44 = db.Column('m_40to44', db.Integer()) 
    m_45to49 = db.Column('m_45to49', db.Integer())
    m_50to54 = db.Column('m_50to54', db.Integer())
    m_55to59 = db.Column('m_55to59', db.Integer()) 
    m_60to61 = db.Column('m_60to61', db.Integer())
    m_62to64 = db.Column('m_62to64', db.Integer())
    m_65to66 = db.Column('m_65to66', db.Integer())
    m_67to69 = db.Column('m_67to69', db.Integer())
    m_70to74 = db.Column('m_70to74', db.Integer())
    m_75to79 = db.Column('m_75to79', db.Integer())
    m_80to84 = db.Column('m_80to84', db.Integer())
    m_85plus = db.Column('m_85plus', db.Integer())
    female = db.Column('female', db.Integer())
    f_under5 = db.Column('f_under5', db.Integer())
    f_5to9  = db.Column('f_5to9', db.Integer())
    f_10to14  = db.Column('f_10to14', db.Integer())
    f_15to17 = db.Column('f_15to17', db.Integer())
    f_18to20 = db.Column('f_18to20', db.Integer())
    f_20  = db.Column('f_20', db.Integer())
    f_21 = db.Column('f_21', db.Integer())
    f_22to24 = db.Column('f_22to24', db.Integer())
    f_25to29 = db.Column('f_25to29', db.Integer())
    f_30to34 = db.Column('f_30to34', db.Integer())
    f_35to39 = db.Column('f_35to39', db.Integer()) 
    f_40to44 = db.Column('f_40to44', db.Integer()) 
    f_45to49 = db.Column('f_45to49', db.Integer())
    f_50to54 = db.Column('f_50to54', db.Integer())
    f_55to59 = db.Column('f_55to59', db.Integer()) 
    f_60to61 = db.Column('f_60to61', db.Integer())
    f_62to64 = db.Column('f_62to64', db.Integer())
    f_65to66 = db.Column('f_65to66', db.Integer())
    f_67to69 = db.Column('f_67to69', db.Integer())
    f_70to74 = db.Column('f_70to74', db.Integer())
    f_75to79 = db.Column('f_75to79', db.Integer())
    f_80to84 = db.Column('f_80to84', db.Integer())
    f_85plus = db.Column('f_85plus', db.Integer())
    
class household_type(db.Model):
    __tablename__='household_type'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())
    family_households = db.Column('family_households', db.Integer())
    family_husband_wife = db.Column('family_husband_wife', db.Integer())
    family_other_family = db.Column('family_other_family', db.Integer())
    family_other_malehouseholder_nowife = db.Column('family_other_malehouseholder_nowife', db.Integer())
    family_other_femalehouseholder_nohusband = db.Column('family_other_femalehouseholder_nohusband', db.Integer())
    nonfamily_households = db.Column('nofamily_households', db.Integer())
    nonfamily_households_livingalone = db.Column('nonfamily_households_livingalone', db.Integer())
    nonfamily_households_notlivingalone = db.Column('nonfamily_households_notlivingalone', db.Integer())


class geographical_mobility_in_last_year(db.Model):
    __tablename__='geographical_mobility_in_last_year'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())    
    same_house = db.Column('same_house', db.Integer())
    diff_house = db.Column('diff_house', db.Integer())
    diff_house_same_metro = db.Column('diff_house_same_metro', db.Integer())
    diff_house_same_metro_movedfromprincipality = db.Column('diff_house_same_metro_movedfromprincipality', db.Integer())
    diff_house_same_metro_movedfromother = db.Column('diff_house_same_metro_movedfromother', db.Integer())
    diff_house_diff_metro = db.Column('diff_house_diff_metro', db.Integer())
    diff_house_diff_metro_movedfromprincipality = db.Column('diff_house_diff_metro_movedfromprincipality', db.Integer())
    diff_house_diff_metro_movedfromother = db.Column('diff_house_diff_metro_movedfromother', db.Integer())
    diff_house_micropolitan_area = db.Column('diff_house_micropolitan_area', db.Integer())
    diff_house_not_metro_or_micro = db.Column('diff_house_not_metro_or_micro', db.Integer())
    abroad = db.Column('abroad', db.Integer())

class sex_by_edu_attainment(db.Model):
    __tablename__='sex_by_edu_attainment'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())
    male = db.Column('male', db.Integer())
    m_no_school = db.Column('m_no_school', db.Integer())
    m_nurseryto4th = db.Column('m_nurseryto4th', db.Integer())
    m_5thand6th = db.Column('m_5thand6th' , db.Integer())
    m_7thand8th = db.Column( 'm_7thand8th', db.Integer())
    m_9th= db.Column( 'm_9th', db.Integer()) 
    m_10th= db.Column( 'm_10th', db.Integer())
    m_11th= db.Column('m_11th' , db.Integer())
    m_12th= db.Column('m_12th' , db.Integer())
    m_hsged= db.Column('m_hsged' , db.Integer())
    m_under1college= db.Column('m_under1college' , db.Integer())
    m_1pluscollege= db.Column('m_1pluscollege', db.Integer())
    m_associates= db.Column('m_associates', db.Integer())
    m_bachelors= db.Column('m_bachelors' , db.Integer())
    m_masters= db.Column('m_masters' , db.Integer())
    m_professional= db.Column( 'm_professional', db.Integer())
    m_doctorate= db.Column('m_doctorate' , db.Integer())
    female = db.Column( 'female', db.Integer())
    f_no_school = db.Column('f_no_school', db.Integer())
    f_nurseryto4th = db.Column('f_nurseryto4th', db.Integer())
    f_5thand6th = db.Column('f_5thand6th' , db.Integer())
    f_7thand8th = db.Column( 'f_7thand8th', db.Integer())
    f_9th= db.Column( 'f_9th', db.Integer()) 
    f_10th= db.Column( 'f_10th', db.Integer())
    f_11th= db.Column('f_11th' , db.Integer())
    f_12th= db.Column('f_12th' , db.Integer())
    f_hsged= db.Column('f_hsged' , db.Integer())
    f_under1college= db.Column('f_under1college' , db.Integer())
    f_1pluscollege= db.Column('f_1pluscollege', db.Integer())
    f_associates= db.Column('f_associates', db.Integer())
    f_bachelors= db.Column('f_bachelors' , db.Integer())
    f_masters= db.Column('f_masters' , db.Integer())
    f_professional= db.Column( 'f_professional', db.Integer())
    f_doctorate= db.Column('f_doctorate' , db.Integer())

class income_povertylvl_ratio(db.Model):
    __tablename__='income_povertylvl_ratio'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())    
    under_onehalf = db.Column('under_onehalf', db.Integer())
    point5_to_point99 = db.Column('point5_to_point99', db.Integer())
    _1_to_1point24 = db.Column('_1_to_1point24', db.Integer())
    _1point25_to_1point49 = db.Column('_1point25_to_1point49', db.Integer())
    _1point5_to_1point84 = db.Column('_1point5_to_1point84', db.Integer())
    _1point85_to_1point99 = db.Column('_1point85_to_1point99', db.Integer())
    _2andover = db.Column('_2andover', db.Integer())


#Haozhang
class race(db.Model):
    __tablename__ = 'race'
    gis_id = db.Column("gis_id", db.String(), primary_key = True)
    region_code = db.Column("region_code", db.Integer)
    state = db.Column("state", db.String())
    state_code = db.Column("state_code", db.Integer)
    county = db.Column("county", db.String())
    county_code = db.Column("county_code", db.Integer)
    census_tract = db.Column("census_tract", db.Integer)
    block_group = db.Column("block_group", db.Integer)
    total = db.Column("total", db.Integer)
    white_alone = db.Column("white_alone", db.Integer)
    black_africanamerican_alone = db.Column("black_africanamerican_alone", db.Integer)
    americanindian_alaskanative_alone = db.Column("americanindian_alaskanative_alone", db.Integer)
    asian_alone = db.Column("asian_alone", db.Integer)
    nativehawaiian_otherpacificislander_alone = db.Column("nativehawaiian_otherpacificislander_alone", db.Integer)
    someotherrace_alone = db.Column("someotherrace_alone", db.Integer)
    two_or_more = db.Column("two_or_more", db.Integer)
    two_or_more_including_someotherrace = db.Column("two_or_more_including_someotherrace", db.Integer)
    two_or_more_excluding_someotherrace = db.Column("two_or_more_excluding_someotherrace", db.Integer)
    

class TranspoTime(db.Model):
    __tablename__ = 'transpo_travel_time_to_work'
    gis_id = db.Column("gis_id", db.String(), primary_key = True)
    region_code = db.Column("region_code", db.Integer)
    state = db.Column("state", db.String())
    state_code = db.Column("state_code", db.Integer)
    county = db.Column("county", db.String())
    county_code = db.Column("county_code", db.Integer)
    census_tract = db.Column("census_tract", db.Integer)
    block_group = db.Column("block_group", db.Integer)
    total = db.Column("total", db.Integer)
    under10 = db.Column("under10", db.Integer)
    _10to14 = db.Column("_10to14", db.Integer)
    _15to19 = db.Column("_15to19", db.Integer)
    _20to24 = db.Column("_20to24", db.Integer)
    _25to29 = db.Column("_25to29", db.Integer)
    _30to34 = db.Column("_30to34", db.Integer)
    _35to44 = db.Column("_35to44", db.Integer)
    _45to59 = db.Column("_60plus", db.Integer)
    _60plus = db.Column("_10to14", db.Integer)
    car_truck_van_alone = db.Column("car_truck_van_alone", db.Integer)
    car_truck_van_alone_under10 = db.Column("car_truck_van_alone_under10", db.Integer)
    car_truck_van_alone_10to14 = db.Column("car_truck_van_alone_10to14", db.Integer)
    car_truck_van_alone_15to19 = db.Column("car_truck_van_alone_15to19", db.Integer)
    car_truck_van_alone_20to24 = db.Column("car_truck_van_alone_20to24", db.Integer)
    car_truck_van_alone_25to29 = db.Column("car_truck_van_alone_25to29", db.Integer)
    car_truck_van_alone_30to34 = db.Column("car_truck_van_alone_30to34", db.Integer)
    car_truck_van_alone_35to44 = db.Column("car_truck_van_alone_35to44", db.Integer)
    car_truck_van_alone_45to59 = db.Column("car_truck_van_alone_45to59", db.Integer)
    car_truck_van_alone_60plus = db.Column("car_truck_van_alone_60plus", db.Integer)
    car_truck_van_carpool = db.Column("car_truck_van_carpool", db.Integer)
    car_truck_van_carpool_under10 = db.Column("car_truck_van_carpool_under10", db.Integer)
    car_truck_van_carpool_10to14 = db.Column("car_truck_van_carpool_10to14", db.Integer)
    car_truck_van_carpool_15to19 = db.Column("car_truck_van_carpool_15to19", db.Integer)
    car_truck_van_carpool_20to24 = db.Column("car_truck_van_carpool_20to24", db.Integer)
    car_truck_van_carpool_25to29 = db.Column("car_truck_van_carpool_25to29", db.Integer)
    car_truck_van_carpool_30to34 = db.Column("car_truck_van_carpool_30to34", db.Integer)
    car_truck_van_carpool_35to44 = db.Column("car_truck_van_carpool_35to44", db.Integer)
    car_truck_van_carpool_45to59 = db.Column("car_truck_van_carpool_45to59", db.Integer)
    car_truck_van_carpool_60plus = db.Column("car_truck_van_carpool_60plus", db.Integer)
    public_transportation = db.Column("public_transportation", db.Integer)
    public_transportation_under10 = db.Column("public_transportation_under10", db.Integer)
    public_transportation_10to14 = db.Column("public_transportation_10to14", db.Integer)
    public_transportation_15to19 = db.Column("public_transportation_15to19", db.Integer)
    public_transportation_20to24 = db.Column("public_transportation_20to24", db.Integer)
    public_transportation_25to29 = db.Column("public_transportation_25to29", db.Integer)
    public_transportation_30to34 = db.Column("public_transportation_30to34", db.Integer)
    public_transportation_35to44 = db.Column("public_transportation_35to44", db.Integer)
    public_transportation_45to59 = db.Column("public_transportation_45to59", db.Integer)
    public_transportation60plus = db.Column("public_transportation60plus", db.Integer)
    taxi_moto_bike_walk = db.Column("taxi_moto_bike_walk", db.Integer)
    taxi_moto_bike_walk_under10 = db.Column("taxi_moto_bike_walk_under10", db.Integer)
    taxi_moto_bike_walk_10to14 = db.Column("taxi_moto_bike_walk_10to14", db.Integer)
    taxi_moto_bike_walk_15to19 = db.Column("taxi_moto_bike_walk_15to19", db.Integer)
    taxi_moto_bike_walk_20to24 = db.Column("taxi_moto_bike_walk_20to24", db.Integer)
    taxi_moto_bike_walk_25to29 = db.Column("taxi_moto_bike_walk_25to29", db.Integer)
    taxi_moto_bike_walk_30to34 = db.Column("taxi_moto_bike_walk_30to34", db.Integer)
    taxi_moto_bike_walk_35to44 = db.Column("taxi_moto_bike_walk_35to44", db.Integer)
    taxi_moto_bike_walk_45to59 = db.Column("taxi_moto_bike_walk_45to59", db.Integer)
    taxi_moto_bike_walk_60plus = db.Column("taxi_moto_bike_walk_60plus", db.Integer)
 
class AgeLanguageEnglish(db.Model):
    __tablename__ = 'age_by_language_by_english_ability'
    gis_id = db.Column("gis_id", db.String(), primary_key = True)
    region_code = db.Column("region_code", db.Integer)
    state = db.Column("state", db.String())
    state_code = db.Column("state_code", db.Integer)
    county = db.Column("county", db.String())
    county_code = db.Column("county_code", db.Integer)
    census_tract = db.Column("census_tract", db.Integer)
    block_group = db.Column("block_group", db.Integer)
    total = db.Column("total", db.Integer)
    _5to17 = db.Column("_5to17", db.Integer)
    _5to17_englishonly = db.Column("_5to17_englishonly", db.Integer)
    _5to17_speakspanish = db.Column("_5to17_speakspanish", db.Integer)
    _5to17_speakspanish_english_verywell = db.Column("_5to17_speakspanish_english_verywell", db.Integer)
    _5to17_speakspanish_english_well = db.Column("_5to17_speakspanish_english_well", db.Integer)
    _5to17_speakspanish_english_notwell = db.Column("_5to17_speakspanish_english_notwell", db.Integer)
    _5to17_speakspanish_english_notatall = db.Column("_5to17_speakspanish_english_notatall", db.Integer)
    _5to17_otherindoeruopean = db.Column("_5to17_otherindoeruopean", db.Integer)
    _5to17_otherindoeruopean_english_verywell = db.Column("_5to17_otherindoeruopean_english_verywell", db.Integer)
    _5to17_otherindoeruopean_english_well = db.Column("_5to17_otherindoeruopean_english_well", db.Integer)
    _5to17_otherindoeruopean_english_notwell = db.Column("_5to17_otherindoeruopean_english_notwell", db.Integer)
    _5to17_otherindoeruopean_english_notatall = db.Column("_5to17_otherindoeruopean_english_notatall", db.Integer)
    _5to17_asianpacificisland = db.Column("_5to17_asianpacificisland", db.Integer)
    _5to17_asianpacificisland_english_verywell = db.Column("_5to17_asianpacificisland_english_verywell", db.Integer)
    _5to17_asianpacificisland_english_well = db.Column("_5to17_asianpacificisland_english_well", db.Integer)
    _5to17_asianpacificisland_english_notwell = db.Column("_5to17_asianpacificisland_english_notwell", db.Integer)
    _5to17_asianpacificisland_english_notatall = db.Column("_5to17_asianpacificisland_english_notatall", db.Integer)
    _5to17_other = db.Column("_5to17_other", db.Integer)
    _5to17_other_english_verywell = db.Column("_5to17_other_english_verywell", db.Integer)
    _5to17_other_english_well = db.Column("_5to17_other_english_well", db.Integer)
    _5to17_other_english_notwell = db.Column("_5to17_other_english_notwell", db.Integer)
    _5to17_other_english_notatall = db.Column("_5to17_other_english_notatall", db.Integer)
    _18to64 = db.Column("_18to64", db.Integer)
    _18to64_englishonly = db.Column("_18to64_englishonly", db.Integer)
    _18to64_speakspanish = db.Column("_18to64_speakspanish", db.Integer)
    _18to64_speakspanish_english_verywell = db.Column("_18to64_speakspanish_english_verywell", db.Integer)
    _18to64_speakspanish_english_well = db.Column("_18to64_speakspanish_english_well", db.Integer)
    _18to64_speakspanish_english_notwell = db.Column("_18to64_speakspanish_english_notwell", db.Integer)
    _18to64_speakspanish_english_notatall = db.Column("_18to64_speakspanish_english_notatall", db.Integer)
    _18to64_otherindoeruopean = db.Column("_18to64_otherindoeruopean", db.Integer)
    _18to64_otherindoeruopean_english_verywell = db.Column("_18to64_otherindoeruopean_english_verywell", db.Integer)
    _18to64_otherindoeruopean_english_well = db.Column("_18to64_otherindoeruopean_english_well", db.Integer)
    _18to64_otherindoeruopean_english_notwell = db.Column("_18to64_otherindoeruopean_english_notwell", db.Integer)
    _18to64_otherindoeruopean_english_notatall = db.Column("_18to64_otherindoeruopean_english_notatall", db.Integer)
    _18to64_asianpacificisland = db.Column("_18to64_asianpacificisland", db.Integer)
    _18to64_asianpacificisland_english_verywell = db.Column("_18to64_asianpacificisland_english_verywell", db.Integer)
    _18to64_asianpacificisland_english_well = db.Column("_18to64_asianpacificisland_english_well", db.Integer)
    _18to64_asianpacificisland_english_notwell = db.Column("_18to64_asianpacificisland_english_notwell", db.Integer)
    _18to64_asianpacificisland_english_notatall = db.Column("_18to64_asianpacificisland_english_notatall", db.Integer)
    _18to64_other = db.Column("_18to64_other", db.Integer)
    _18to64_other_english_verywell = db.Column("_18to64_other_english_verywell", db.Integer)
    _18to64_other_english_well = db.Column("_18to64_other_english_well", db.Integer)
    _18to64_other_english_notwell = db.Column("_18to64_other_english_notwell", db.Integer)
    _18to64_other_english_notatall = db.Column("_18to64_other_english_notatall", db.Integer)
    _65plus = db.Column("_65plus", db.Integer)
    _65plus_englishonly = db.Column("_65plus_englishonly", db.Integer)
    _65plus_speakspanish = db.Column("_65plus_speakspanish", db.Integer)
    _65plus_speakspanish_english_verywell = db.Column("_65plus_speakspanish_english_verywell", db.Integer)
    _65plus_speakspanish_english_well = db.Column("_65plus_speakspanish_english_well", db.Integer)
    _65plus_speakspanish_english_notwell = db.Column("_65plus_speakspanish_english_notwell", db.Integer)
    _65plus_speakspanish_english_notatall = db.Column("_65plus_speakspanish_english_notatall", db.Integer)
    _65plus_otherindoeruopean = db.Column("_65plus_otherindoeruopean", db.Integer)
    _65plus_otherindoeruopean_english_verywell = db.Column("_65plus_otherindoeruopean_english_verywell", db.Integer)
    _65plus_otherindoeruopean_english_well = db.Column("_65plus_otherindoeruopean_english_well", db.Integer)
    _65plus_otherindoeruopean_english_notwell = db.Column("_65plus_otherindoeruopean_english_notwell", db.Integer)
    _65plus_otherindoeruopean_english_notatall = db.Column("_65plus_otherindoeruopean_english_notatall", db.Integer)
    _65plus_asianpacificisland = db.Column("_65plus_asianpacificisland", db.Integer)
    _65plus_asianpacificisland_english_verywell = db.Column("_65plus_asianpacificisland_english_verywell", db.Integer)
    _65plus_asianpacificisland_english_well = db.Column("_65plus_asianpacificisland_english_well", db.Integer)
    _65plus_asianpacificisland_english_notwell = db.Column("_65plus_asianpacificisland_english_notwell", db.Integer)
    _65plus_asianpacificisland_english_notatall = db.Column("_65plus_asianpacificisland_english_notatall", db.Integer)
    _65plus_other = db.Column("_65plus_other", db.Integer)
    _65plus_other_english_verywell = db.Column("_65plus_other_english_verywell", db.Integer)
    _65plus_other_english_well = db.Column("_65plus_other_english_well", db.Integer)
    _65plus_other_english_notwell = db.Column("_65plus_other_english_notwell", db.Integer)
    _65plus_other_english_notatall = db.Column("_65plus_other_english_notatall", db.Integer)
   
class PublicAssistIncomeHouseholds(db.Model):
    __tablename__ = 'public_assistance_income_households'
    gis_id = db.Column("gis_id", db.String(), primary_key = True)
    region_code = db.Column("region_code", db.Integer)
    state = db.Column("state", db.String())
    state_code = db.Column("state_code", db.Integer)
    county = db.Column("county", db.String())
    county_code = db.Column("county_code", db.Integer)
    census_tract = db.Column("census_tract", db.Integer)
    block_group = db.Column("block_group", db.Integer)
    total = db.Column("total", db.Integer)  
    with_public_assistance = db.Column("with_public_assistance", db.Integer)
    no_public_assitsance = db.Column("no_public_assitsance", db.Integer)
    
class PerCapitaIncome2010Dollars(db.Model):
    __tablename__ = 'per_capita_income_2010dollars'
    gis_id = db.Column("gis_id", db.String(), primary_key = True)
    region_code = db.Column("region_code", db.Integer)
    state = db.Column("state", db.String())
    state_code = db.Column("state_code", db.Integer)
    county = db.Column("county", db.String())
    county_code = db.Column("county_code", db.Integer)
    census_tract = db.Column("census_tract", db.Integer)
    block_group = db.Column("block_group", db.Integer)
    per_capita_income_past_year = db.Column("per_capita_income_past_year", db.Integer)

#Rayan
class sex_by_workstatus_by_hoursperweek_by_weeksperyear(db.Model):
    __tablename__ = 'sex_by_workstatus_by_hoursperweek_by_weeksperyear'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())
    male = db.Column('male', db.Integer())
    m_worked = db.Column('m_worked', db.Integer())
    m_worked_35plushrs = db.Column('m_worked_35plushrs', db.Integer())
    m_worked_35plushrs_50to52weeks = db.Column('m_worked_35plushrs_50to52weeks', db.Integer())
    m_worked_35plushrs_48to49weeks = db.Column('m_worked_35plushrs_48to49weeks', db.Integer())
    m_worked_35plushrs_40to47weeks = db.Column('m_worked_35plushrs_40to47weeks', db.Integer())
    m_worked_35plushrs_27to39weeks = db.Column('m_worked_35plushrs_27to39weeks', db.Integer())
    m_worked_35plushrs_14to26weeks = db.Column('m_worked_35plushrs_14to26weeks', db.Integer())
    m_worked_35plushrs_1to13weeks = db.Column('m_worked_35plushrs_1to13weeks', db.Integer())
    m_worked_15to34hrs = db.Column('m_worked_15to34hrs', db.Integer())
    m_worked_15to34hrs_50to52weeks = db.Column('m_worked_15to34hrs_50to52weeks', db.Integer())
    m_worked_15to34hrs_48to49weeks = db.Column('m_worked_15to34hrs_48to49weeks', db.Integer())
    m_worked_15to34hrs_40to47weeks = db.Column('m_worked_15to34hrs_40to47weeks', db.Integer())
    m_worked_15to34hrs_27to39weeks = db.Column('m_worked_15to34hrs_27to39weeks', db.Integer())
    m_worked_15to34hrs_14to26weeks = db.Column('m_worked_15to34hrs_14to26weeks', db.Integer())
    m_worked_15to34hrs_1to13weeks = db.Column('m_worked_15to34hrs_1to13weeks', db.Integer())
    
    m_worked_1to14hrs = db.Column('m_worked_15to34hrs', db.Integer())
    m_worked_1to14hrs_50to52weeks = db.Column('m_worked_1to14hrs_50to52weeks', db.Integer())
    m_worked_1to14hrs_48to49weeks = db.Column('m_worked_1to14hrs_48to49weeks', db.Integer())
    m_worked_1to14hrs_40to47weeks = db.Column('m_worked_1to14hrs_40to47weeks', db.Integer())
    m_worked_1to14hrs_27to39weeks = db.Column('m_worked_1to14hrs_27to39weeks', db.Integer())
    m_worked_1to14hrs_14to26weeks = db.Column('m_worked_1to14hrs_14to26weeks', db.Integer())
    m_worked_1to14hrs_1to13weeks = db.Column('m_worked_1to14hrs_1to13weeks', db.Integer())
    
    m_didnotwork = db.Column('m_didnotwork', db.Integer())
    
    female = db.Column('female', db.Integer())
    f_worked = db.Column('f_worked', db.Integer())
    
    f_worked_35plushrs = db.Column('m_worked_35plushrs', db.Integer())
    f_worked_35plushrs_50to52weeks = db.Column('f_worked_35plushrs_50to52weeks', db.Integer())
    f_worked_35plushrs_48to49weeks = db.Column('f_worked_35plushrs_48to49weeks', db.Integer())
    f_worked_35plushrs_40to47weeks = db.Column('f_worked_35plushrs_40to47weeks', db.Integer())
    f_worked_35plushrs_27to39weeks = db.Column('f_worked_35plushrs_27to39weeks', db.Integer())
    f_worked_35plushrs_14to26weeks = db.Column('f_worked_35plushrs_14to26weeks', db.Integer())
    f_worked_35plushrs_1to13weeks = db.Column('f_worked_35plushrs_1to13weeks', db.Integer())
    
    f_worked_15to34hrs = db.Column('f_worked_15to34hrs', db.Integer())
    f_worked_15to34hrs_50to52weeks = db.Column('f_worked_15to34hrs_50to52weeks', db.Integer())
    f_worked_15to34hrs_48to49weeks = db.Column('f_worked_15to34hrs_48to49weeks', db.Integer())
    f_worked_15to34hrs_40to47weeks = db.Column('f_worked_15to34hrs_40to47weeks', db.Integer())
    f_worked_15to34hrs_27to39weeks = db.Column('f_worked_15to34hrs_27to39weeks', db.Integer())
    f_worked_15to34hrs_14to26weeks = db.Column('f_worked_15to34hrs_14to26weeks', db.Integer())
    f_worked_15to34hrs_1to13weeks = db.Column('f_worked_15to34hrs_1to13weeks', db.Integer())
    
    f_worked_1to14hrs = db.Column('f_worked_15to34hrs', db.Integer())
    f_worked_1to14hrs_50to52weeks = db.Column('f_worked_1to14hrs_50to52weeks', db.Integer())
    f_worked_1to14hrs_48to49weeks = db.Column('f_worked_1to14hrs_48to49weeks', db.Integer())
    f_worked_1to14hrs_40to47weeks = db.Column('f_worked_1to14hrs_40to47weeks', db.Integer())
    f_worked_1to14hrs_27to39weeks = db.Column('f_worked_1to14hrs_27to39weeks', db.Integer())
    f_worked_1to14hrs_14to26weeks = db.Column('f_worked_1to14hrs_14to26weeks', db.Integer())
    f_worked_1to14hrs_1to13weeks = db.Column('f_worked_1to14hrs_1to13weeks', db.Integer())
    
    f_didnotwork = db.Column('f_didnotwork', db.Integer())

class imputation_citizen_status(db.Model):
    __tablename__ = 'imputation_citizen_status'
    gis_id = db.Column('gis_id', db.String(), primary_key=True)
    region_code = db.Column('region_code', db.Integer())
    state = db.Column('state', db.String())
    state_code = db.Column('state_code', db.Integer())
    county = db.Column('county', db.String())
    county_code = db.Column('county_code', db.Integer())
    census_tract = db.Column('census_tract', db.Integer())
    block_group = db.Column('block_group', db.Integer())
    total = db.Column('total', db.Integer())
    native = db.Column('native', db.Integer())
    native_imputed = db.Column('native_imputed', db.Integer())
    native_not_imputed = db.Column('native_not_imputed', db.Integer())
    foreign_born = db.Column('foreign_born', db.Integer())
    foreign_born_imputed = db.Column('foreign_born_imputed', db.Integer())
    foreign_born_not_imputed = db.Column('foreign_born_not_imputed', db.Integer())
   
class tract_data(db.Model):
    __tablename__ = 'tract_data'
    state_abbrev = db.Column('state_abbrev', db.String())
    geoid = db.Column('geoid', db.String(), primary_key=True)
    population = db.Column('population', db.Integer())
    hu = db.Column('hu', db.Integer())
    aland_sqmi=db.Column('aland_sqmi', db.Float())
    awater_sqmi=db.Column('awater_sqmi', db.Float())
    latitude = db.Column('latitude', db.Float())
    longitude = db.Column('longitude', db.Float())    

    



