CREATE TABLE sex_by_age(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total INT,
	male INT,
	m_under5 INT, m_5to9 INT, m_10to14 INT, m_15to17 INT, m_18to20 INT, m_20 INT, m_21 INT, m_22to24 INT, m_25to29 INT, m_30to34 INT, m_35to39 int, 
	m_40to44 int, m_45to49 int, m_50to54 int, m_55to59 int, m_60to61 int, m_62to64 int, m_65to66 int, m_67to69 int, m_70to74 int, m_75to79 int, m_80to84 int, m_85plus int,
	female INT,
	f_under5 INT, f_5to9 INT, f_10to14 INT, f_15to17 INT, f_18to20 INT, f_20 INT, f_21 INT, f_22to24 INT, f_25to29 INT, f_30to34 INT, f_35to39 int, 
	f_40to44 int, f_45to49 int, f_50to54 int, f_55to59 int, f_60to61 int, f_62to64 int, f_65to66 int, f_67to69 int, f_70to74 int, f_75to79 int, f_80to84 int, f_85plus int
	);

CREATE TABLE household_type(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	family_households int,
	family_husband_wife int,
	family_other_family int,
	family_other_malehouseholder_nowife int,
	family_other_femalehouseholder_nohusband int,
	nonfamily_households int,
	nonfamily_householder_livingalone int,
	nonfamily_householder_notlivingalone int
	);

CREATE TABLE race(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	white_alone int,
	black_africanamerican_alone int,
	americanindian_alaskanative_alone int,
	asian_alone int,
	nativehawaiian_otherpacificislander_alone int,
	someotherrace_alone int,
	two_or_more int,
	two_or_more_including_someotherrace int,
	two_or_more_excluding_someotherrace INT
);

CREATE TABLE geographical_mobility_in_last_year(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	same_house int,
	diff_house int,
	diff_house_same_metro int,
	diff_house_same_metro_movedfromprincipality int,
	diff_house_same_metro_movedfromother int,
	diff_house_diff_metro int,
	diff_house_diff_metro_movedfromprincipality int,
	diff_house_diff_metro_movedfromother int,
	diff_house_micropolitan_area int,
	diff_house_not_metro_or_micro int,
	abroad INT
);

CREATE TABLE transpo_travel_time_to_work(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	under10 int,
	_10to14 int,
	_15to19 int,
	_20to24 int,
	_25to29 int,
	_30to34 int,
	_35to44 int,
	_45to59 int,
	_60plus int,
	car_truck_van_alone int,
	car_truck_van_alone_under10 int,
	car_truck_van_alone_10to14 int,
	car_truck_van_alone_15to19 int,
	car_truck_van_alone_20to24 int,
	car_truck_van_alone_25to29 int,
	car_truck_van_alone_30to34 int,
	car_truck_van_alone_35to44 int,
	car_truck_van_alone_45to59 int,
	car_truck_van_alone_60plus int,
	car_truck_van_carpool int,
	car_truck_van_carpool_under10 int,
	car_truck_van_carpool_10to14 int,
	car_truck_van_carpool_15to19 int,
	car_truck_van_carpool_20to24 int,
	car_truck_van_carpool_25to29 int,
	car_truck_van_carpool_30to34 int,
	car_truck_van_carpool_35to44 int,
	car_truck_van_carpool_45to59 int,
	car_truck_van_carpool_60plus int,
	public_transportation int,
	public_transportation_under10 int,
	public_transportation_10to14 int,
	public_transportation_15to19 int,
	public_transportation_20to24 int,
	public_transportation_25to29 int,
	public_transportation_30to34 int,
	public_transportation_35to44 int,
	public_transportation_45to59 int,
	public_transportation60plus int,
	taxi_moto_bike_walk int,
	taxi_moto_bike_walk_under10 int,
	taxi_moto_bike_walk_10to14 int,
	taxi_moto_bike_walk_15to19 int,
	taxi_moto_bike_walk_20to24 int,
	taxi_moto_bike_walk_25to29 int,
	taxi_moto_bike_walk_30to34 int,
	taxi_moto_bike_walk_35to44 int,
	taxi_moto_bike_walk_45to59 int,
	taxi_moto_bike_walk_60plus int
);

CREATE TABLE sex_by_edu_attainment_25plus(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	male int,
	m_no_school int,
	m_nurseryto4th int,
	m_5thand6th int,
	m_7thand8th int,
	m_9th int,
	m_10th int,
	m_11th int,
	m_12th int,
	m_hs_ged int,
	m_under1college int,
	m_1pluscollege int,
	m_associates int,
	m_bachelors int,
	m_masters int,
	m_professional int,
	m_doctorate int,
	female int,
	f_no_school int,
	f_nurseryto4th int,
	f_5thand6th int,
	f_7thand8th int,
	f_9th int,
	f_10th int,
	f_11th int,
	f_12th int,
	f_hs_ged int,
	f_under1college int,
	f_1pluscollege int,
	f_associates int,
	f_bachelors int,
	f_masters int,
	f_professional int,
	f_doctorate int
);

CREATE TABLE age_by_language_by_english_ability(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	_5to17 int,
	_5to17_englishonly int,
	_5to17_speakspanish int,
	_5to17_speakspanish_english_verywell int,
	_5to17_speakspanish_english_well int,
	_5to17_speakspanish_english_notwell int,
	_5to17_speakspanish_english_notatall int,
	_5to17_otherindoeruopean int,
	_5to17_otherindoeruopean_english_verywell int,
	_5to17_otherindoeruopean_english_well int,
	_5to17_otherindoeruopean_english_notwell int,
	_5to17_otherindoeruopean_english_notatall int,
	_5to17_asianpacificisland int,
	_5to17_asianpacificisland_english_verywell int,
	_5to17_asianpacificisland_english_well int,
	_5to17_asianpacificisland_english_notwell int,
	_5to17_asianpacificisland_english_notatall int,
	_5to17_other int,
	_5to17_other_english_verywell int,
	_5to17_other_english_well int,
	_5to17_other_english_notwell int,
	_5to17_other_english_notatall int,
	_18to64 int,
	_18to64_englishonly int,
	_18to64_speakspanish int,
	_18to64_speakspanish_english_verywell int,
	_18to64_speakspanish_english_well int,
	_18to64_speakspanish_english_notwell int,
	_18to64_speakspanish_english_notatall int,
	_18to64_otherindoeruopean int,
	_18to64_otherindoeruopean_english_verywell int,
	_18to64_otherindoeruopean_english_well int,
	_18to64_otherindoeruopean_english_notwell int,
	_18to64_otherindoeruopean_english_notatall int,
	_18to64_asianpacificisland int,
	_18to64_asianpacificisland_english_verywell int,
	_18to64_asianpacificisland_english_well int,
	_18to64_asianpacificisland_english_notwell int,
	_18to64_asianpacificisland_english_notatall int,
	_18to64_other int,
	_18to64_other_english_verywell int,
	_18to64_other_english_well int,
	_18to64_other_english_notwell int,
	_18to64_other_english_notatall int,
	_65plus int,
	_65plus_englishonly int,
	_65plus_speakspanish int,
	_65plus_speakspanish_english_verywell int,
	_65plus_speakspanish_english_well int,
	_65plus_speakspanish_english_notwell int,
	_65plus_speakspanish_english_notatall int,
	_65plus_otherindoeruopean int,
	_65plus_otherindoeruopean_english_verywell int,
	_65plus_otherindoeruopean_english_well int,
	_65plus_otherindoeruopean_english_notwell int,
	_65plus_otherindoeruopean_english_notatall int,
	_65plus_asianpacificisland int,
	_65plus_asianpacificisland_english_verywell int,
	_65plus_asianpacificisland_english_well int,
	_65plus_asianpacificisland_english_notwell int,
	_65plus_asianpacificisland_english_notatall int,
	_65plus_other int,
	_65plus_other_english_verywell int,
	_65plus_other_english_well int,
	_65plus_other_english_notwell int,
	_65plus_other_english_notatall int
);

CREATE TABLE income_povertylvl_ratio(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	under_onehalf int,
	point5_to_point99 int,
	_1_to_1point24 int,
	_1point25_to_1point49 int,
	_1point5_to_1point84 int,
	_1point85_to_1point99 int,
	_2andover int
);

CREATE TABLE public_assistance_income_households(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	with_public_assistance int,
	no_public_assitsance int
);

CREATE TABLE per_capita_income_2010dollars(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	per_capita_income_past_year int
);

CREATE TABLE sex_by_workstatus_by_hoursperweek_by_weeksperyear(gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	census_tract INT,
	block_group INT,
	total int,
	male int,
	m_worked int,
	m_worked_35plushrs int,
	m_worked_35plushrs_50to52weeks int,
	m_worked_35plushrs_48to49weeks int,
	m_worked_35plushrs_40to47weeks int,
	m_worked_35plushrs_27to39weeks int,
	m_worked_35plushrs_14to26weeks int,
	m_worked_35plushrs_1to13weeks int,
	m_worked_15to34hrs int,
	m_worked_15to34hrs_50to52weeks int,
	m_worked_15to34hrs_48to49weeks int,
	m_worked_15to34hrs_40to47weeks int,
	m_worked_15to34hrs_27to39weeks int,
	m_worked_15to34hrs_14to26weeks int,
	m_worked_15to34hrs_1to13weeks int,
	m_worked_1to14hrs int,
	m_worked_1to14hrs_50to52weeks int,
	m_worked_1to14hrs_48to49weeks int,
	m_worked_1to14hrs_40to47weeks int,
	m_worked_1to14hrs_27to39weeks int,
	m_worked_1to14hrs_14to26weeks int,
	m_worked_1to14hrs_1to13weeks int,
	m_didnotwork int,
	female int,
	f_worked int,
	f_worked_35plushrs int,
	f_worked_35plushrs_50to52weeks int,
	f_worked_35plushrs_48to49weeks int,
	f_worked_35plushrs_40to47weeks int,
	f_worked_35plushrs_27to39weeks int,
	f_worked_35plushrs_14to26weeks int,
	f_worked_35plushrs_1to13weeks int,
	f_worked_15to34hrs int,
	f_worked_15to34hrs_50to52weeks int,
	f_worked_15to34hrs_48to49weeks int,
	f_worked_15to34hrs_40to47weeks int,
	f_worked_15to34hrs_27to39weeks int,
	f_worked_15to34hrs_14to26weeks int,
	f_worked_15to34hrs_1to13weeks int,
	f_worked_1to14hrs int,
	f_worked_1to14hrs_50to52weeks int,
	f_worked_1to14hrs_48to49weeks int,
	f_worked_1to14hrs_40to47weeks int,
	f_worked_1to14hrs_27to39weeks int,
	f_worked_1to14hrs_14to26weeks int,
	f_worked_1to14hrs_1to13weeks int,
	f_didnotwork int
);

CREATE TABLE imputation_citizen_status (gis_id VARCHAR NOT NULL PRIMARY KEY,
	region_code INT,
	state VARCHAR,
	state_code INT,
	county VARCHAR,
	county_code INT,
	total int,
	census_tract INT,
	block_group INT,
	
	native int,
	native_imputed int,
	native_not_imputed int,
	foreign_born int,
	foreign_born_imputed int,
	foreign_born_not_imputed int
);

CREATE TABLE tract_data(state_abbrev VARCHAR,
	geoid VARCHAR NOT NULL PRIMARY KEY,
	population int,
	hu int,
	aland_sqmi decimal,
	awater_sqmi decimal,
	latitude decimal,
	longitude decimal)
